language: julia

os:
    - linux

julia:
    - 1.0
    - 1.1
    - nightly

matrix:
    fast_finish: true
    allow_failures:
    - julia: nightly

notifications:
    email: false

after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("NilsTFPackage")); Codecov.submit(Codecov.process_folder())'
